

**Laboratory Task 3**

Instruction: Perform a forward and backward propagation in python using the inputs from Laboratory Task 2

In [ ]:
import numpy as np

x = np.array([1, 0, 1])
y = np.array([1])

# use relu as the activation function.

# learning rate
lr = 0.001

In [2]:
def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)

In [3]:
# Hidden layer weights
W_hidden = np.array([
    [0.2, -0.3],
    [0.4,  0.1],
    [-0.5, 0.2]
])

# Hidden layer biases
b_hidden = np.array([-0.4, 0.2])

# Output layer weights
W_output = np.array([-0.3, -0.2])

# Output layer bias
b_output = 0.1

In [5]:
# Hidden layer weighted sum
Z_hidden = np.dot(x, W_hidden) + b_hidden

print("Z_hidden =", Z_hidden)

Z_hidden = [-0.7  0.1]


In [6]:
# Hidden layer activation
H = relu(Z_hidden)

print("Hidden layer output =", H)

Hidden layer output = [0.  0.1]


In [7]:
# Output layer weighted sum
Z_output = np.dot(H, W_output) + b_output

print("Z_output =", Z_output)

Z_output = 0.08


In [8]:
# Output activation
y_hat = relu(Z_output)

print("Predicted output =", y_hat)

Predicted output = 0.08


In [9]:
# Calculate error
error = 0.5 * (y - y_hat) ** 2

print("Error =", error)

Error = [0.4232]


In [10]:
# Gradient of error with respect to predicted output
dE_dyhat = y_hat - y

# Gradient through output ReLU
dE_dZ_output = dE_dyhat * relu_derivative(Z_output)

print("dE/dy_hat =", dE_dyhat)
print("dE/dZ_output =", dE_dZ_output)

dE/dy_hat = [-0.92]
dE/dZ_output = [-0.92]


In [11]:
# Gradients for output layer weights and bias
dE_dW_output = H * dE_dZ_output
dE_db_output = dE_dZ_output

print("dE/dW_output =", dE_dW_output)
print("dE/db_output =", dE_db_output)

dE/dW_output = [-0.    -0.092]
dE/db_output = [-0.92]


In [12]:
# Gradient flowing back to hidden layer
dE_dH = W_output * dE_dZ_output

# Gradient through hidden ReLU
dE_dZ_hidden = dE_dH * relu_derivative(Z_hidden)

print("dE/dH =", dE_dH)
print("dE/dZ_hidden =", dE_dZ_hidden)

dE/dH = [0.276 0.184]
dE/dZ_hidden = [0.    0.184]


In [13]:
# Gradient for hidden layer weights
dE_dW_hidden = np.outer(x, dE_dZ_hidden)

# Gradient for hidden layer biases
dE_db_hidden = dE_dZ_hidden

print("dE/dW_hidden =")
print(dE_dW_hidden)

print("dE/db_hidden =", dE_db_hidden)

dE/dW_hidden =
[[0.    0.184]
 [0.    0.   ]
 [0.    0.184]]
dE/db_hidden = [0.    0.184]


In [14]:
# Update output layer weights and bias
W_output = W_output - lr * dE_dW_output
b_output = b_output - lr * dE_db_output

print("Updated output weights:")
print(W_output)

print("Updated output bias:")
print(b_output)

Updated output weights:
[-0.3      -0.199908]
Updated output bias:
[0.10092]


In [15]:
print("========== FINAL RESULTS ==========")

print("\nForward Propagation:")
print("Z_hidden =", Z_hidden)
print("H =", H)
print("Z_output =", Z_output)
print("Predicted output =", y_hat)
print("Error =", error)

print("\nBackward Propagation:")
print("dE/dW_output =", dE_dW_output)
print("dE/db_output =", dE_db_output)
print("dE/dW_hidden =")
print(dE_dW_hidden)
print("dE/db_hidden =", dE_db_hidden)

print("\nUpdated Parameters:")
print("W_hidden =")
print(W_hidden)
print("b_hidden =", b_hidden)
print("W_output =", W_output)
print("b_output =", b_output)

========== FINAL RESULTS ==========

Forward Propagation:
Z_hidden = [-0.7  0.1]
H = [0.  0.1]
Z_output = 0.08
Predicted output = 0.08
Error = [0.4232]

Backward Propagation:
dE/dW_output = [-0.    -0.092]
dE/db_output = [-0.92]
dE/dW_hidden =
[[0.    0.184]
 [0.    0.   ]
 [0.    0.184]]
dE/db_hidden = [0.    0.184]

Updated Parameters:
W_hidden =
[[ 0.2 -0.3]
 [ 0.4  0.1]
 [-0.5  0.2]]
b_hidden = [-0.4  0.2]
W_output = [-0.3      -0.199908]
b_output = [0.10092]
