Laboratory Task 5
1. Perform Standard Imports


2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.


3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.


4. Create a tensor "x" from the array above


5. Change the dtype of x from int32 to int64


6. Reshape x into a 3x2 tensor
There are several ways to do this.


7. Return the right-hand column of tensor x


8. Without changing x, return a tensor of square values of x
There are several ways to do this.


9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.
Think about what shape it should have to permit matrix multiplication.


10. Find the matrix product of x and y.

In [1]:
import torch
import numpy as np

In [2]:
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

In [3]:
set_seed(42)

arr = np.random.randint(0, 5, 6)

print(arr)

[3 4 2 4 4 1]


In [4]:
x = torch.from_numpy(arr)

print(x)

tensor([3, 4, 2, 4, 4, 1])


In [5]:
x = x.to(torch.int64)

print(x)
print(x.dtype)

tensor([3, 4, 2, 4, 4, 1])
torch.int64


In [6]:
x = x.reshape(3, 2)

print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [7]:
right_column = x[:, 1]

print(right_column)

tensor([4, 4, 1])


In [8]:
squared_x = x ** 2

print(squared_x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [9]:
set_seed(42)

y = torch.randint(0, 5, (2, 3), dtype=torch.int64)

print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


In [10]:
product = x @ y

print(product)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
